language: c
before_install:
- sudo apt-get -qq update
- sudo apt-get install -y make libxinerama-dev libxext-dev libx11-dev build-essential
  binutils-mingw-w64-i686 gcc-mingw-w64-i686 g++-mingw-w64-i686
script: make cnping cnping.exe
  
deploy:
  provider: releases
  api_key:
    secure: "nG/v9mBb2bCmXaB/yxkqR7jlQiCt3KwWiz7cWQiAwjmbDn6oS+z6LQm4IkGVcJOoW4Su+fKv0uxKmybC68lnCI4TtDvvjYFh6/SXMaEAtYVXIe7lVsq0q8ptPrhFiz1JFJoVz1neHLZy/QC4vv38BdsbkVBA5Du2ouC1otQnYWYwWUaKJnmYZqwA+0QrDNPe+XYl2CGc83PjA7QmEKW9Q6WGlMA9+9o4eDVcPYAyqdvEPFPNAZKDfXEX91IMsJmxDa5Pb0496s4L2As9TDIbPEcd3GKRsjlZ0koS5pIs/61thpsh4hJqzO7wD17/qx0rXg942wf6XkSIC/DEzmZCViBEDnKvukI/8z0/VxLdVAdSJd2rA8PPglECQ1XW1RyhJNlYYi4EkPfewvIczX/1m6ljKhHFciyd45d/iIZrMf6uAOLASKR2rWJ754fozN8+z+cz5y77Wo3Kg1X1Lm+OPpHNU4S3Dx0XXbUuzmVNnr5M+1n73CHRUX/eDvnmoVJ0CMPCJcJcAINdok/BVIEJ1RRnouDyW9J00/XgnZJpMztUDI29O+/XrrFF3ybWdLPW+qU9yyekPJGg0oKVOdFR9MddtO4B7uwwufBdXh0+iEIfKSDFNmVk4Thdgziny+j+pN92I3zL0YHFbuU1yCtEPKKurJ6ySQj/yKEcpZ4gF+4="
  file: 
    - cnping.exe
  skip_cleanup: true
  on:
    tags: true
    repo: dreua/cnping
    branch: travis-integration
